$(var ns):
  controller_manager:
    ros__parameters:
      update_rate: 20

      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster

      vg_controller:
        type: position_controllers/GripperActionController
        
  vg_controller:
    ros__parameters:
      joint: _suction_regulator_joint
      # Add these lines to relax the requirements:
      allow_stalling: true
      # This tells the controller it doesn't need a velocity state interface
      check_joint_velocity_at_goal: false

