# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

controller_names:
  - /onrobot/vg_controller

/onrobot/vg_controller:
  type: GripperCommand
  action_ns: gripper_cmd
  default: true
  joints: 
    - _suction_regulator_joint
